name: Build
on:
  issue_comment:
    types: [created, edited]
env:
  maintainers: '["skulltech", "mdhrumil"]'
  trigger: ~build

jobs:
  build:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, env.trigger) &&
      contains(fromJson(env.maintainers), github.event.comment.user.login)

    name: Building something
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Henlo
        run: |
          echo "Hello world!"
          sleep 60
          echo "Bye world!"

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
